on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy repository manifest
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup
        run: mkdir out out-reso
      - name: Build modular-avatar repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/modular-avatar
          package: nadena.dev.modular-avatar
          repo_url: https://vpm.nadena.dev/vpm.json
          prerelease_repo_url: https://vpm.nadena.dev/vpm-prerelease.json
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          prerelease_repo_id: dev.nadena.prerelease
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build NDMF repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/ndmf
          package: nadena.dev.ndmf
          repo_url: https://vpm.nadena.dev/vpm.json
          prerelease_repo_url: https://vpm.nadena.dev/vpm-prerelease.json
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          prerelease_repo_id: dev.nadena.prerelease
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build misc tools repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/misc-vrc-tools
          package: nadena.dev.misc-vrc-tools
          repo_url: https://vpm.nadena.dev/vpm.json
          prerelease_repo_url: https://vpm.nadena.dev/vpm-prerelease.json
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          prerelease_repo_id: dev.nadena.prerelease
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build resonite repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out-reso
          repository: bdunderscore/modular-avatar-resonite
          package: nadena.dev.modular-avatar.resonite
          repo_url: https://vpm.nadena.dev/vpm-reso-dup.json
          prerelease_repo_url: https://vpm.nadena.dev/vpm-reso.json
          repo_author: bd_
          repo_name: Modular Avatar - Resonite Support
          repo_id: dev.nadena.vpm.resonite
          prerelease_repo_id: dev.nadena.vpm.resonite
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -lR .

      - run: mv out-reso/vpm-reso.json out/vpm-reso.json
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
