on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy repository manifest
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup
        run: mkdir out out-reso



      - name: Laod prior version of repository
        run: |
          mkdir out-test
          #curl -f -o out/vpm.json https://vpm.nadena.dev/vpm.json || rm -f out/vpm.json
      
      - name: Build NDMF repository
        uses: bdunderscore/vpm-repo-list-generator@test-dist
        with:
          output: out
          repository: bdunderscore/ndmf
          package: nadena.dev.ndmf
          repo_url: https://vpm.nadena.dev/vpm.json
          doc_url: https://ndmf.nadena.dev
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Build modular-avatar repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/modular-avatar
          package: nadena.dev.modular-avatar
          repo_url: https://vpm.nadena.dev/vpm.json
          doc_url: "https://modular-avatar.nadena.dev/?lang=auto"
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build misc tools repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/misc-vrc-tools
          package: nadena.dev.misc-vrc-tools
          repo_url: https://vpm.nadena.dev/vpm.json
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build resonite repository
        uses: bdunderscore/vpm-repo-list-generator@dist
        with:
          output: out
          repository: bdunderscore/modular-avatar-resonite
          package: nadena.dev.modular-avatar.resonite
          repo_url: https://vpm.nadena.dev/vpm.json
          repo_author: bd_
          repo_name: bd_
          repo_id: dev.nadena.vpm
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: ls -lR .

      - run: cp out/vpm.json out/vpm-reso.json
      - run: cp out/vpm.json out/vpm-prerelease.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
